trainer:
  stop_early: False
  max_epochs: 200
  devices: 1
  strategy: 'deepspeed_stage_3'
  accelerator: 'gpu'
  fp: 32
  gas: 8
  debug_mode: False

data:
  data_dir: '/Users/sunlin/Documents/workdir/ieer/infromationExtractorInBFQB-main/data/'
  raw_file_type: 'json'
  max_seq_length: 128
  train_batchsize: 2
  valid_batchsize: 2
  do_eval_only: False
  num_workers: 0
  
model:
  base_model: bert-base-chinese
  train_batchsize: 2
  #cache_dir: '/Volumes/T7/FileBackup/lora_model/llama_opemlmlab'
  load_checkpoint: False
  ckpt_dir: '/root/autodl-tmp/ckpt/20230707_llam_whole/last.ckpt'
  weight_decay: 0.1
  learning_rate: 0.0001
  warmup_ratio: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 0.00000001

ckpt:
  dirpath: ckpt
  monitor: 'train_loss'
  save_top_k: 1
  mode: 'min'
  every_n_train_steps: 500
  save_weights_only: True
  save_last: True
  file_name: 'Default'